### ISSUE TITLE
Tracking: Glimmer Standalone

### ISSUE THREAD

**Issue by josemarluedke** [josemarluedke/glimmer-apollo#1]
This issue is for tracking the work necessary to make this project compatible with Glimmer Standalone (no Ember).

- [x] Ember Resources (ember-could-get-used-to-this) https://github.com/pzuraq/ember-could-get-used-to-this/issues/24 - #3
- [x] `@ember/test-waiters` https://github.com/emberjs/ember-test-waiters/issues/243 or [an alternative](https://github.com/devlato/async-wait-until)  - #3
- [x] Translate ember imports to glimmer - #3
- [x] Pre-build TS into JS #4
  - [x] Ship types #4
  - [x] Ship commonjs #4 
  - [x] Ship modules #4
  - [x] Ship source maps
- [ ] Embroider Safe
- [ ] Embroider V2
  - [ ] Depends on ember-auto-import v2 shim  https://github.com/ef4/ember-auto-import/pull/376
  - [ ] Remove `ember-cli-typescript`.
  - [ ] Remove `ember-cli-babel`
  - [ ] Remove `ember-auto-import`
- [ ] Create test apps
  - [x] Glimmer #4
  - [x] Ember
- [ ] Add tests & demos to apps
  - [ ] Glimmer
  - [ ] Ember
